FROM postgres:16.6

RUN localedef -i ru_RU -c -f UTF-8 -A /usr/share/locale/locale.alias ru_RU.UTF-8


ENV LANG ru_RU.utf8 
		#POSTGRES_USER=my_cw \
		#POSTGRES_PASSWORD=qwerty \
		#POSTGRES_DB=pis_cw 

CMD ["postgres"]