development:
  adapter: redis
  url: redis://redis-service-alias:6379/1
  channel_prefix: ror_service_development

test:
  adapter: test

#production:
#  adapter: redis
#  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#  channel_prefix: ror_service_production

production:
  adapter: redis
  url: redis://redis-service-alias:6379/1
  channel_prefix: ror_service_production
