
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PSQL_MY_CW_NAME"] %>
  password: <%= ENV["PSQL_MY_CW_PASS"] %>
  database: <%= ENV["PIS_DATA_BASE"] %>

  host: db-ps  
  port: 5432
  

development:
  <<: *default

test:
  <<: *default  

production:
  <<: *default

my_dev:
  <<: *default  
  host: localhost